### ISSUE TITLE
Create an option to activate the sampling script in a nextflow pipe

### ISSUE THREAD

**Issue by fabfabBesnard** [fabfabBesnard/Parallel-Variant-Calling#7]
Desired behavior: in the config file for an analysis, if the option 'sample' (or something equivalent + the fraction - but default value is also good) is provided, the pipe will be run on a new sampling from original read

**Comment by maliktalbi** [comment]
option --sample available in the pipeline. You just have to put the --sample option with a fraction of the pipe ( number between 0 and 1).

**Comment by maliktalbi** [comment]
Add the Empty_sample_dir process to check and to empty the sample repository
